export const colors = [
    { letter: "A", color: "#b3ffff" },
    { letter: "B", color: "#8080ff" },
    { letter: "C", color: "#acecb7" },
    { letter: "D", color: "#5abedc" },
    { letter: "E", color: "#b3b3ff" },
    { letter: "F", color: "#33ccff" },
    { letter: "G", color: "#e9f7fb" },
    { letter: "H", color: "#46dcd2" },
    { letter: "I", color: "#42b4d7" },
    { letter: "J", color: "#64dc78" },
    { letter: "K", color: "#93d7eb" },
    { letter: "L", color: "#53bfdf" },
    { letter: "M", color: "#29d6cb" },
    { letter: "N", color: "#44d55c" },
    { letter: "O", color: "#3399ff" },
    { letter: "P", color: "#28aed7" },
    { letter: "Q", color: "#ffccff" },
    { letter: "R", color: "#80bfff" },
    { letter: "S", color: "#d4f7f4" },
    { letter: "T", color: "#a9efe9" },
    { letter: "U", color: "#bff3ef" },
    { letter: "V", color: "#eaf7fb" },
    { letter: "W", color: "#219134" },
    { letter: "X", color: "#28d7c9" },
    { letter: "Y", color: "#c1f1c9" },
    { letter: "Z", color: "#99ffcc" },
];
